// Generated by CoffeeScript 1.3.3
(function() {
  var fakeSpriteSheet;

  fakeSpriteSheet = function(width, height, color) {
    var canvas, ctxt;
    canvas = document.createElement('canvas');
    canvas.height = height;
    canvas.width = width;
    ctxt = canvas.getContext('2d');
    ctxt.fillStyle = color;
    ctxt.fillRect(0, 0, width, height);
    return {
      image: {
        data: canvas
      }
    };
  };

  window.textureAtlasTest = function() {
    var atlas, cont;
    cont = document.getElementById('cont');
    atlas = new cc.TextureAtlas(512, 512);
    cont.appendChild(atlas._canvas);
    atlas.addSpriteSheet(fakeSpriteSheet(200, 128, 'purple'));
    atlas.addSpriteSheet(fakeSpriteSheet(200, 64, 'red'));
    return atlas.addSpriteSheet(fakeSpriteSheet(200, 64, 'blue'));
  };

}).call(this);
