// Generated by CoffeeScript 1.3.3
(function() {
  var fakeSpriteSheet, showTexture;

  fakeSpriteSheet = function(width, height) {
    var canvas, ctxt;
    canvas = document.createElement('canvas');
    canvas.height = height;
    canvas.width = width;
    ctxt = canvas.getContext('2d');
    ctxt.strokeStyle = 'red';
    ctxt.fillStyle = 'yellow';
    ctxt.strokeRect(0, 0, width, height);
    ctxt.fillRect(1, 1, width - 2, height - 2);
    return {
      image: {
        data: canvas
      }
    };
  };

  showTexture = function() {
    var canvas, colIdx, colWidth, ctxt, row, x, y, _i, _j, _len, _ref, _ref1, _results;
    ctxt = cont.getContext('2d');
    ctxt.globalAlpha = 1;
    ctxt.fillStyle = 'white';
    ctxt.fillRect(0, 0, 512, 512);
    canvas = atlas._canvases[idx];
    ctxt.drawImage(canvas, 0, 0);
    count.innerHTML = "Showing " + (idx + 1) + " of " + atlas._canvases.length + " textures<br/>";
    count.innerHTML += "Press number keys to switch between textures, c to show texture atlas grid.";
    if (showTextureGrid) {
      ctxt.globalAlpha = 0.4;
      ctxt.fillStyle = 'green';
      ctxt.strokeStyle = 'black';
      x = y = 0;
      _ref = canvas.rows;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        row = _ref[_i];
        for (colIdx = _j = 0, _ref1 = canvas.colWidth.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; colIdx = 0 <= _ref1 ? ++_j : --_j) {
          colWidth = canvas.colWidth[colIdx];
          ctxt.strokeRect(x, y, colWidth, row.height);
          if (row.cells[colIdx]) {
            ctxt.fillRect(x + 1, y + 1, colWidth - 2, row.height - 2);
          }
          x += colWidth;
        }
        x = 0;
        _results.push(y += row.height);
      }
      return _results;
    }
  };

  window.textureAtlasTest = function() {
    window.idx = 0;
    window.showTextureGrid = false;
    window.onkeypress = function(e) {
      var id;
      if (e.which === 'c'.charCodeAt(0)) {
        window.showTextureGrid = !window.showTextureGrid;
        return showTexture();
      } else {
        id = e.which - 49;
        if (id === -1) {
          id = 9;
        }
        if ((0 <= id && id < atlas._canvases.length)) {
          window.idx = id;
          return showTexture();
        }
      }
    };
    window.cont = document.getElementById('cont');
    window.count = document.getElementById('count');
    window.atlas = new cc.TextureAtlas(512, 512);
    atlas.addSpriteSheet(fakeSpriteSheet(200, 128));
    atlas.addSpriteSheet(fakeSpriteSheet(200, 64));
    atlas.addSpriteSheet(fakeSpriteSheet(150, 64));
    atlas.addSpriteSheet(fakeSpriteSheet(20, 128));
    return showTexture();
  };

}).call(this);
